parameters:

services:

    # Pour la redirection aprés l'authentification
    authentication.handler.login_success_handler:
        class:  AppBundle\Redirection\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']

    admin.projet:
        class: AppBundle\Admin\AdminProjet
        arguments: [~, AppBundle\Entity\Projet, ~]
        tags:
            - { name: sonata.admin, manager_type: orm,group: "Projet", label: Projet ,icon: '<i class="fa fa-vcard-o"></i>' }
        public: true

    admin.Client:
        class: AppBundle\Admin\AdminClient
        arguments: [~, AppBundle\Entity\Client, ~]
        tags:
          - { name: sonata.admin, manager_type: orm,group: "Client", label: Client ,icon: '<i class="fa fa-user"></i>'}
        public: true

